language: node_js
node_js:
  - "10.16.3"
yarn:
  - "1.15.2"

script: echo "Running against node: $(node -v), yarn: ${yarn -v}..."

install:
  - yarn install --pure-lockfile

jobs:
  include:
    - stage: Test
      script: yarn test

    - stage: Lint
      script: yarn lint

    -stage: Release
      if: branch = master
      script: yarn release
