language: node_js
node_js:
 - "10"

install:
 - yarn install --pure-lockfile

jobs:
 include:
   - stage: "Test"
     script: yarn test
   - stage: "Lint"
     script: yarn lint
   - stage: "Build"
     script: yarn build
